### ISSUE TITLE
请问下部署服务器上remoteBind应该填什么

### ISSUE THREAD

**Issue by Siyuan-Zheng** [CreditTone/mitmproxy-java#1]
应用代理设置的地址为服务器外网ip，我尝试在代理服务的remoteBind字段中填服务器外网地址或127.0.0.1，均不起作用

**Comment by CreditTone** [comment]
你mitmproxy-hub启动在哪个服务器，你就填哪个服务器的ip

**Comment by CreditTone** [comment]
如果本地启动hub的话，你就可以填127.0.0.1
